In [1]:
import numpy as np
import pandas as pd
import torch
shape = (36,64,400,1280)
data = np.random.rand(*shape)
print(data.shape)
a=[0, 1145, 45239, 1128, 294, 1247, 1157, 301, 5866, 499, 673, 658, 706, 5287, 334, 2264, 1208, 437, 326, 1300, 314, 500, 402, 1379, 6517, 9715, 2838, 264, 649, 12772, 2645, 320, 606, 262, 1512, 381, 13530, 756, 262, 1135, 360, 18008, 909, 386, 1253, 2410, 1277, 399, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
print(len(a))

(36, 64, 400, 1280)
400


##### 看一下提取出的激活

In [2]:
from datasets import Dataset
import pandas as pd
import torch as th
import numpy as np

/mnt/data1/xyliu/.conda/envs/xyliuEnv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# 读取 .arrow 文件
dataset = Dataset.from_file('dataset/protgpt2_ctrlprot_dataset/cc-test-activation1.arrow')
dataset2 = Dataset.from_file('dataset/protgpt2_ctrlprot_dataset/cc-test-activation2.arrow')
dataset3 = Dataset.from_file('dataset/protgpt2_ctrlprot_dataset/cc-test-activation3.arrow')
dataset4 = Dataset.from_file('dataset/protgpt2_ctrlprot_dataset/cc-test-activation4.arrow')
dataset5 = Dataset.from_file('dataset/protgpt2_ctrlprot_dataset/cc-valid-activation1.arrow')
dataset6 = Dataset.from_file('dataset/protgpt2_ctrlprot_dataset/cc-valid-activation2.arrow')
dataset7 = Dataset.from_file('dataset/protgpt2_ctrlprot_dataset/cc-valid-activation3.arrow')
# 将数据集转换为 Pandas DataFrame
df = dataset.to_pandas()
# 追加dataset2到df
df = pd.concat([df, dataset2.to_pandas()], axis=0)
df_test = pd.concat([df, dataset3.to_pandas()], axis=0)
df_test = pd.concat([df_test, dataset4.to_pandas()], axis=0)

df_valid = dataset5.to_pandas()
df_valid = pd.concat([df_valid, dataset6.to_pandas()], axis=0)
df_valid = pd.concat([df_valid, dataset7.to_pandas()], axis=0)
print(df_valid.shape)
print(df_test.shape)
df_valid = df_valid[['entry', 'mlp_activation']]
df_test = df_test[['entry', 'mlp_activation']]
# df的entry列更名为proteins
df_valid = df_valid.rename(columns={'entry': 'proteins'})
df_test = df_test.rename(columns={'entry': 'proteins'})

In [21]:
df_test.head(3)

proteins                                     mlp_activation   index  \
0  TTBK2_HUMAN  [[-0.0, -0.0, -0.05545, -0.000871, -0.0008364,...  498587   
1   SPS1_HUMAN  [[-0.0, -0.0, -0.0447, -0.00977, -0.0008445, -...  451797   
2   DOPD_HUMAN  [[-0.0, -0.0, -0.0, -0.0, -0.000864, -0.0, -0....  107169   

                                          accessions   genes  \
0                    Q6IQ55; O94932; Q6ZN52; Q8IVV1;  146057   
1  P49903; B4DWK0; D3DRS9; D6PSQ9; Q5T5U8; Q5T5U9...   22929   
2            P30046; B7Z522; O00774; O60787; Q13534;    1652   

                                           sequences  \
0  MSGGGEQLDILSVGILVKERWKVLRKIGGGGFGEIYDALDMLTREN...   
1  MSTRESFNPESYELDKSFRLTRFTELKGTGCKVPQDVLQKLLESLQ...   
2  MPFLELDTNLPANRVPAGLEKRLCAAAASILGKPADRVNVTVRPGL...   

                                         annotations              string_ids  \
0  [GO:0005814|IDA, GO:0036064|ISS, GO:0035869|ID...  [9606.ENSP00000267890]   
1  [GO:0005737|IDA, GO:0031965|IDA, GO:0005886|ID...  [9606.ENSP00000367893]   
2  [GO:0005737|IEA, GO:0070062|HDA, GO:0005615|ID...  [9606.ENSP00000381386]   

   orgs                                    exp_annotations  \
0  9606  [GO:0005814, GO:0035869, GO:0005829, GO:000561...   
1  9606  [GO:0005737, GO:0031965, GO:0005886, GO:000552...   
2  9606  [GO:0070062, GO:0005615, GO:0005126, GO:000416...   

                                    prop_annotations  cafa_target  \
0  [GO:0005615, GO:0051128, GO:0022607, GO:004819...         True   
1  [GO:0005737, GO:0006807, GO:0043170, GO:004322...         True   
2  [GO:0005615, GO:1903557, GO:0040013, GO:004323...         True   

                                                esm2  \
0  [-0.013188319, -0.0053996695, 0.025485538, -0....   
1  [-0.052441664, -0.01151562, 0.004816029, -0.04...   
2  [0.019176578, -0.022834094, -0.03292651, 0.019...   

                                            mf_preds  
0  [1.4522190294741222e-07, 0.07912817038595676, ...  
1  [1.7025577125906466e-07, 0.4242278002202511, 0...  
2  [6.3777714558455045e-06, 0.01592439296655357, ...

In [22]:
print(type(df_test['mlp_activation'][0]))
df_test['mlp_activation'][0]

<class 'numpy.ndarray'>


array([array([-0.      , -0.      , -0.05545 , ..., -0.01631 , -0.01091 ,
              -0.008644], dtype=float16)                                 ,
       array([-0., -0., -0., ..., -0., -0., -0.], dtype=float16),
       array([-0., -0., -0., ..., -0., -0., -0.], dtype=float16),
       array([-0.      , -0.000827, -0.      , ..., -0.      , -0.      ,
              -0.      ], dtype=float16)                                 ,
       array([-0.      , -0.      , -0.      , ..., -0.000875, -0.      ,
              -0.      ], dtype=float16)                                 ,
       array([-0.005566 , -0.       , -0.       , ..., -0.       , -0.       ,
              -0.0008616], dtype=float16)                                     ,
       array([-0.      , -0.003628, -0.      , ..., -0.      , -0.      ,
              -0.      ], dtype=float16)                                 ,
       array([-0.       , -0.       , -0.       , ..., -0.       , -0.0008326,
              -0.       ], dtype=f

In [18]:
import pandas as pd

data = {
    'proteins': ['A', 'B', 'C'],
    'mlp_activation': [
        [[0.1, 0.2, 0.3],[0.4,0.5,0.6]],
        [0.4, 0.5, 0.6],
        [0.7, 0.8, 0.9]
    ]
}
df_t = pd.DataFrame(data)

# 获取 'mlp_activation' 列的第一个单元格的值
value = df_t['mlp_activation'][0]
print(value)  # 输出: [0.1, 0.2, 0.3]
df_t.head()

[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]


proteins                      mlp_activation
0        A  [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]
1        B                     [0.4, 0.5, 0.6]
2        C                     [0.7, 0.8, 0.9]

In [11]:
for i, row in enumerate(df_test.itertuples()):
    print(row.mlp_activation.shape)
    print(len(row.mlp_activation[0]))
    if i==3:
        break

(36,)
5120
(36,)
5120
(36,)
5120
(36,)
5120


In [2]:
origin_test_df = pd.read_pickle('../deepgo2/data/cc/test_data.pkl')
origin_valid_df = pd.read_pickle('../deepgo2/data/cc/valid_data.pkl')
# 统计origin_df的proteins列中的字符串是否有重名
# print(origin_df['proteins'].duplicated().sum())
# # 输出origin_df的proteins列中名为FPGS1_ARATH，ASPH_HUMAN，XANP_ECOLI的行
# print(origin_df[origin_df['proteins'].isin(['FPGS1_ARATH', 'ASPH_HUMAN', 'XANP_ECOLI'])])

# 去除origin_test_df和origin_valid_df的interpros和esm列
origin_test_df = origin_test_df.drop(columns=['interpros', 'esm'])
origin_valid_df = origin_valid_df.drop(columns=['interpros', 'esm'])
print(origin_test_df.shape)
print(origin_valid_df.shape)
origin_test_df.head(3)

(4221, 13)
(2964, 13)


index     proteins               accessions   genes  \
49724  314306  PLPK1_ARATH          Q9LXB8; Q940G9;  830812   
34968  221052    LGT_ECOLI  P60955; P37149; Q2MA09;  947303   
34969  221154    LGT_MYCTU  P9WK93; L0TA60; O06131;  885292   

                                               sequences  \
49724  MALMKKSLSAALLSSPLLIICLIALLADPFSVGARRLLEDPKPEIP...   
34968  MTSSYLHFPEFDPVIFSIGPVALHWYGLMYLVGFIFAMWLATRRAN...   
34969  MRMLPSYIPSPPRGVWYLGPLPVRAYAVCVITGIIVALLIGDRRLT...   

                                             annotations          string_ids  \
49724  [GO:0005576|IEA, GO:0009505|IDA, GO:0010030|IM...  [3702.AT5G09530.1]   
34968  [GO:0009898|IDA, GO:0005887|IDA, GO:0005886|ID...      [511145.b2828]   
34969   [GO:0005887|HDA, GO:0008961|IEA, GO:0042158|IEA]      [83332.Rv1614]   

        orgs                                    exp_annotations  \
49724   3702   [GO:0009505, GO:0010030, GO:0009791, GO:2000028]   
34968  83333  [GO:0009898, GO:0005887, GO:0005886, GO:000896...   
34969  83332                                       [GO:0005887]   

                                        prop_annotations  cafa_target  \
49724  [GO:1900140, GO:0005618, GO:0022414, GO:000962...         True   
34968  [GO:0008961, GO:0006807, GO:0043170, GO:001675...         True   
34969  [GO:0110165, GO:0005887, GO:0071944, GO:001602...        False   

                                                    esm2  \
49724  [-0.018137017, -0.0033944978, 0.07022466, -0.0...   
34968  [0.008079203, 0.012723313, -0.0049987854, -0.0...   
34969  [0.05481643, 0.023382254, 0.0073699257, 0.0091...   

                                                mf_preds  
49724  [0.05110101914033294, 0.1570896878838539, 0.16...  
34968  [6.938631802455575e-07, 0.07264955807477236, 0...  
34969  [2.7665545161426053e-06, 0.189385823905468, 0....

In [19]:
# 将df和origin_df合并，根据proteins列合并
df_test = pd.merge(df_test, origin_test_df, on='proteins')
print(df_test.shape)
df_valid = pd.merge(df_valid, origin_valid_df, on='proteins')
print(df_valid.shape)
df_valid.head()

(4221, 14)
(2964, 14)


proteins                                     mlp_activation   index  \
0   NAT9_SCHPO  [[-0.0, -0.0, -0.01732, -0.0, -0.0008163, -0.0...  269339   
1  ARC2B_XENLA  [[-0.0, -0.0, -0.02695, -0.0, -0.0008717, -0.0...   21258   
2   DPP1_YEAST  [[-0.0, -0.0, -0.00681, -0.0, -0.000868, -0.0,...  108591   
3   OUTS_DICD3  [[-0.0, -0.0, -0.003672, -0.0, -0.0008435, -0....  295619   
4  Y1514_ARATH  [[-0.0, -0.0, -0.001607, -0.0, -0.0, -0.02182,...  529623   

                accessions    genes  \
0                  Q9USR6;  2540260   
1                  Q6IRB1;   432109   
2          Q05521; D6VSR4;   851878   
3          Q01567; E0SM45;  9734629   
4  Q9FRK5; Q8GY41; Q9C9Q7;   843851   

                                           sequences  \
0  MKINQNTTVDCGNLILVPYQKCHVLKYHNWMKNEELQELTCSEPLT...   
1  MILLEVNNRIIEEILTLKFENAAAGNKPEVVEVTFADFDGVLYHVS...   
2  MNRVSFIKTPFNIGAKWRLEDVFLLIIMILLNYPVYYQQPFERQFY...   
3  MHVSSLKVVLFGVCCLSLAACQTPAPVKNTASRSAASVPANEQISQ...   
4  MADSQNGKSAFFFFFVSLILLFLSPSYSDVTASESDPIPYENSDAS...   

                                         annotations              string_ids  \
0  [GO:0005829|HDA, GO:0005634|HDA, GO:0008080|IS...    [4896.SPBC577.03c.1]   
1  [GO:0005885|IDA, GO:0042995|IEA, GO:0005737|IE...                      []   
2  [GO:0000329|IDA, GO:0016021|IEA, GO:0000810|ID...          [4932.YDR284C]   
3   [GO:0009279|IDA, GO:0006886|IEA, GO:0016485|IDA]  [198628.Dda3937_02411]   
4   [GO:0005783|IDA, GO:0016021|IEA, GO:0005739|HDA]      [3702.AT1G75140.1]   

     orgs                                    exp_annotations  \
0  284812                           [GO:0005829, GO:0005634]   
1    8355               [GO:0005885, GO:0005634, GO:0035861]   
2  559292  [GO:0000329, GO:0000810, GO:0042802, GO:000819...   
3  198628                           [GO:0009279, GO:0016485]   
4    3702                           [GO:0005783, GO:0005739]   

                                    prop_annotations  cafa_target  \
0  [GO:0005737, GO:0110165, GO:0043227, GO:000562...         True   
1  [GO:0043232, GO:0005856, GO:0043227, GO:004322...        False   
2  [GO:0005737, GO:0006793, GO:0043227, GO:004425...         True   
3  [GO:0043170, GO:0008152, GO:0071704, GO:003031...        False   
4  [GO:0005737, GO:0043227, GO:0043229, GO:007194...         True   

                                                esm2  \
0  [-0.0108210305, 0.03376122, 0.00796709, -0.017...   
1  [-0.013940236, -0.081527345, 0.009427608, -0.0...   
2  [0.013267661, 0.0330246, 0.032625966, -0.00897...   
3  [-0.032567836, -0.08163681, 0.0123141715, -0.0...   
4  [-0.05389887, -0.0007063134, 0.023593688, -0.0...   

                                            mf_preds  
0  [1.8080542041332137e-07, 0.0013366428902372718...  
1  [7.680370799789671e-06, 0.033907188568264246, ...  
2  [8.542913789710838e-07, 0.003321899101138115, ...  
3  [6.657555491074163e-05, 0.019355675438418984, ...  
4  [8.960727518569911e-05, 0.1888891365379095, 0....

In [20]:
df_valid.to_pickle('../deepgo2/data/cc/valid_gpt_data.pkl')
df_test.to_pickle('../deepgo2/data/cc/test_gpt_data.pkl')

In [3]:
dataset_train = Dataset.from_file('dataset/protgpt2_ctrlprot_dataset/data-00000-of-00049.arrow')
df_train = dataset_train.to_pandas()
# 用for循环读取剩余的35个.arrow文件，并将其转换为Pandas DataFrame，然后追加到df_train
for i in range(1, 49):
    dataset = Dataset.from_file(f'dataset/protgpt2_ctrlprot_dataset/data-000{i:02}-of-00049.arrow')
    df_train = pd.concat([df_train, dataset.to_pandas()], axis=0)

print(df_train.shape)
df_train.head(3)

(52072, 4)


entry                                           sequence  \
0  GBRA2_HUMAN  MKTKLNIYNMQFLLFVFLVWDPARLVLANIQEDEAKNNITIFTRIL...   
1  SPAST_HUMAN  MNSPGGRGKKKGSGGASNPVPPRPPPPCLAPAPPAAGPAPPPESPH...   
2   TF3A_SCHPO  MCHFNELSIEIESKNLRSAKKIFHCPYEECGKKYSRPSLLEQHLRT...   

                                     head_activation  \
0  [[0.12054, -0.2708, -0.1453, -0.5493, 0.694, 0...   
1  [[0.665, 0.1704, -0.3687, 0.4463, 0.4587, 0.58...   
2  [[1.014, 0.318, -0.5454, 0.03668, -0.1211, -0....   

                                      mlp_activation  
0  [[-0.0, -0.0, -0.1044, -0.002329, -0.0, -0.0, ...  
1  [[-0.0, -0.0, -0.008026, -0.0008473, -0.000874...  
2  [[-0.0, -0.0, -0.08057, -0.0, -0.0, -0.002289,...

In [4]:
df_train = df_train[['entry','sequence', 'mlp_activation']]
origin_train_df = pd.read_pickle('../deepgo2/data/cc/train_data.pkl')
origin_train_df = origin_train_df.drop(columns=['interpros', 'esm'])
print(origin_train_df.shape)
# 统计origin_df的proteins列中的字符串是否有重名
print(origin_train_df['proteins'].duplicated().sum())
origin_train_df.head(3)

(52072, 13)
0


index    proteins       accessions    genes  \
39691  253628  MRT2_CAEEL          G5EC44;   176608   
47190  302420  PCNA_YEAST  P15873; D6VQ89;   852385   
47188  302408  PCNA_SCHPO          Q03392;  2540020   

                                               sequences  \
39691  MMELETGQCTIMELKKENVKELAQVFKTVAFKDTGTWHASEAGMKI...   
47190  MLEAKFEEASLFKRIIDGFKDCVQLVNFQCKEDGIIAQAVDDSRVL...   
47188  MLEARFQQAALLKKLLDAIKELVTDANFDCNDNGISLQAMDSSHVA...   

                                             annotations  \
39691  [GO:0030896|IBA, GO:0005634|IC, GO:0008408|IBA...   
47190  [GO:0000781|IEA, GO:0005634|IDA, GO:0043626|IP...   
47188  [GO:0000785|IDA, GO:0005829|HDA, GO:0043596|ID...   

                  string_ids    orgs  \
39691       [6239.Y41C4A.14]    6239   
47190         [4932.YBR088C]  559292   
47188  [4896.SPBC16D10.09.1]  284812   

                                         exp_annotations  \
39691  [GO:0005634, GO:0000077, GO:0008630, GO:000628...   
47190  [GO:0005634, GO:0043626, GO:0005657, GO:003033...   
47188  [GO:0000785, GO:0005829, GO:0043596, GO:000565...   

                                        prop_annotations  cafa_target  \
39691  [GO:1901576, GO:0022607, GO:0044271, GO:009719...         True   
47190  [GO:0006273, GO:0098687, GO:1901576, GO:002260...         True   
47188  [GO:0006273, GO:1901576, GO:0071840, GO:000962...         True   

                                                    esm2  \
39691  [-0.068327904, 0.0889695, -0.06085973, -0.0209...   
47190  [-0.049562298, 0.124328926, -0.084678374, -0.0...   
47188  [-0.06278011, 0.095311135, -0.11708009, -0.051...   

                                                mf_preds  
39691  [6.776121153961867e-06, 0.01035898586269468, 0...  
47190  [7.192755134610707e-06, 0.035333055071532726, ...  
47188  [3.991257557345307e-06, 0.022228094516322017, ...

In [5]:
df_train = df_train[['entry', 'mlp_activation']]
df_train = df_train.rename(columns={'entry': 'proteins'})
df_train = pd.merge(df_train, origin_train_df, on='proteins')
print(df_train.shape)
df_train.head(3)

(52072, 14)


proteins                                     mlp_activation   index  \
0  GBRA2_HUMAN  [[-0.0, -0.0, -0.1044, -0.002329, -0.0, -0.0, ...  148952   
1  SPAST_HUMAN  [[-0.0, -0.0, -0.008026, -0.0008473, -0.000874...  449762   
2   TF3A_SCHPO  [[-0.0, -0.0, -0.08057, -0.0, -0.0, -0.002289,...  478198   

                        accessions    genes  \
0  P47869; A8K0U7; B7Z1H8; Q59G14;     2555   
1          Q9UBP0; A7E2A7; Q9UPR9;     6683   
2                          Q9UTL5;  2542887   

                                           sequences  \
0  MKTKLNIYNMQFLLFVFLVWDPARLVLANIQEDEAKNNITIFTRIL...   
1  MNSPGGRGKKKGSGGASNPVPPRPPPPCLAPAPPAAGPAPPPESPH...   
2  MCHFNELSIEIESKNLRSAKKIFHCPYEECGKKYSRPSLLEQHLRT...   

                                         annotations              string_ids  \
0  [GO:0030424|IEA, GO:0034707|IEA, GO:0032590|IB...  [9606.ENSP00000421828]   
1  [GO:1904115|IEA, GO:0005813|IEA, GO:0005737|ID...  [9606.ENSP00000480893]   
2  [GO:0005829|HDA, GO:0005634|HDA, GO:0008097|ID...    [4896.SPAC144.09c.1]   

     orgs                                    exp_annotations  \
0    9606  [GO:1902711, GO:0030285, GO:0005886, GO:000850...   
1    9606  [GO:0005737, GO:0031410, GO:0005829, GO:007178...   
2  284812  [GO:0005829, GO:0005634, GO:0008097, GO:000367...   

                                    prop_annotations  cafa_target  \
0  [GO:0015276, GO:0015267, GO:1902476, GO:009879...         True   
1  [GO:0005615, GO:0031984, GO:0043014, GO:003250...         True   
2  [GO:1901576, GO:0044271, GO:0016070, GO:000672...         True   

                                                esm2  \
0  [-0.124218255, -0.0005950727, -0.0031139634, -...   
1  [0.03724686, -0.0016410591, -0.016298689, -0.0...   
2  [0.05888844, 0.0008618344, 0.0095522925, -0.03...   

                                            mf_preds  
0  [5.990657498955443e-07, 0.0032978959497995675,...  
1  [8.367739923187401e-07, 0.038408617954701185, ...  
2  [3.6484390619762053e-07, 0.0011763554794015363...

In [7]:
df_train.to_pickle('../deepgo2/data/cc/train_gpt_data.pkl')

In [ ]:
th.set_printoptions(edgeitems=5)
data = th.zeros((len(df), 5120), dtype=th.float32)
for i, row in enumerate(df.itertuples()):
        # Data vector
        data[i, :] = th.FloatTensor(row.mlp_activation[0])
        print(data)