In [1]:
import numpy as np
import pandas as pd
import torch
shape = (36,64,400,1280)
data = np.random.rand(*shape)
print(data.shape)
a=[0, 1145, 45239, 1128, 294, 1247, 1157, 301, 5866, 499, 673, 658, 706, 5287, 334, 2264, 1208, 437, 326, 1300, 314, 500, 402, 1379, 6517, 9715, 2838, 264, 649, 12772, 2645, 320, 606, 262, 1512, 381, 13530, 756, 262, 1135, 360, 18008, 909, 386, 1253, 2410, 1277, 399, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
print(len(a))

(36, 64, 400, 1280)
400


### 看一下提取出的激活and合并保存测试/验证激活

In [1]:
from datasets import Dataset
import pandas as pd
import torch as th
import numpy as np

/mnt/data1/xyliu/.conda/envs/xyliuEnv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# 读取 .arrow 文件
dataset = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-test-data1.arrow')
dataset2 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-test-data2.arrow')
dataset3 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-test-data3.arrow')
dataset4 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-test-data4.arrow')
dataset8 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-test-data5.arrow')
dataset9 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-test-data6.arrow')
dataset5 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-valid-data1.arrow')
dataset6 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-valid-data2.arrow')
dataset7 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-valid-data3.arrow')
dataset10 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-valid-data4.arrow')
dataset11 = Dataset.from_file('dataset/esm2_ctrlprot_dataset/bp-valid-data5.arrow')
# 将数据集转换为 Pandas DataFrame
df = dataset.to_pandas()
# 追加dataset2到df
df = pd.concat([df, dataset2.to_pandas()], axis=0)
df_test = pd.concat([df, dataset3.to_pandas()], axis=0)
df_test = pd.concat([df_test, dataset4.to_pandas()], axis=0)
df_test = pd.concat([df_test, dataset8.to_pandas()], axis=0)
df_test = pd.concat([df_test, dataset9.to_pandas()], axis=0)


df_valid = dataset5.to_pandas()
df_valid = pd.concat([df_valid, dataset6.to_pandas()], axis=0)
df_valid = pd.concat([df_valid, dataset7.to_pandas()], axis=0)
df_valid = pd.concat([df_valid, dataset10.to_pandas()], axis=0)
df_valid = pd.concat([df_valid, dataset11.to_pandas()], axis=0)

print(df_valid.shape)
print(df_test.shape)
df_valid.head(3)

(2870, 4)
(3275, 4)


entry                                           sequence  \
0  I17RC_HUMAN  MPVPWFLLSLALGRSPVVLSLERLVGPQDATHCSPVSLEPWGDEER...   
1   CGS5_YEAST  MGENHDHEQSIKRNSMIYNENERQLCNSNLKILQNKRALSKNDSSS...   
2   TCP9_ARATH  MATIQKLEEVAGKDQTLRAVDLTIINGVRNVETSRPFQVNPTVSLE...   

                                     head_activation  \
0  [[1.092963, -0.62294304, -0.027228814, 0.31922...   
1  [[0.62033427, -0.42075673, -0.02369591, 0.3242...   
2  [[0.6293054, -0.95022905, -0.025146635, 0.4432...   

                                      mlp_activation  
0  [[-2.6853547, -2.1375146, -2.2823002, -6.11868...  
1  [[-3.4853284, -3.28391, -1.6440333, -5.988611,...  
2  [[-3.0722506, -3.5439043, -1.5122703, -5.96197...

In [3]:
df_valid = df_valid[['entry', 'head_activation', 'mlp_activation']]
df_test = df_test[['entry', 'head_activation', 'mlp_activation']]
# df的entry列更名为proteins
df_valid = df_valid.rename(columns={'entry': 'proteins'})
df_test = df_test.rename(columns={'entry': 'proteins'})

In [4]:
df_test.head(3)

proteins                                    head_activation  \
0  MU118_SCHPO  [[0.71064043, -0.78373, 0.17843433, 0.44866693...   
1  RIBF2_ARATH  [[0.80387986, -0.92246854, 0.13989517, 0.37234...   
2    PROM2_RAT  [[1.1022087, -1.1226231, -0.24359038, 0.554247...   

                                      mlp_activation  
0  [[-3.464381, -2.7741058, 0.38177404, -6.432429...  
1  [[-3.3184495, -2.5963278, -1.862722, -6.173691...  
2  [[-2.92977, -2.0233755, -2.6876519, -5.9608927...

In [6]:
for i, row in enumerate(df_test.itertuples()):
    print(row.head_activation.shape)
    print(len(row.head_activation[0]))
    if i==2:
        break

(33,)
1280
(33,)
1280
(33,)
1280
(33,)
1280


In [16]:
for i, row in enumerate(df_test.itertuples()):
    print(row.head_activation[32])
    if i==2:
        break
for i, row in enumerate(df_test.itertuples()):
    print(row.mlp_activation[0])
    if i==2:
        break

[-0.28436467 -3.75038    -1.3116606  ... -5.3674083   0.9831759
 -2.763052  ]
[ 1.2971684 -6.855271   5.680663  ... -2.850386  -2.8798747  5.2801647]
[ 5.730257   3.3768992 -2.7631528 ... -3.2401297  2.8146896  1.828335 ]
[-3.464381   -2.7741058   0.38177404 ... -4.6602454  -2.4757476
 -3.956944  ]
[-3.3184495 -2.5963278 -1.862722  ... -4.4335504 -4.1271152 -3.6418521]
[-2.92977   -2.0233755 -2.6876519 ... -4.6217446 -3.565572  -3.9695535]


In [5]:
origin_test_df = pd.read_pickle('../deepgo2/data/bp/test_data.pkl')
origin_valid_df = pd.read_pickle('../deepgo2/data/bp/valid_data.pkl')
# 统计origin_df的proteins列中的字符串是否有重名
# print(origin_df['proteins'].duplicated().sum())
# # 输出origin_df的proteins列中名为FPGS1_ARATH，ASPH_HUMAN，XANP_ECOLI的行
# print(origin_df[origin_df['proteins'].isin(['FPGS1_ARATH', 'ASPH_HUMAN', 'XANP_ECOLI'])])

# 去除origin_test_df和origin_valid_df的interpros和esm列
origin_test_df = origin_test_df.drop(columns=['interpros', 'esm'])
origin_valid_df = origin_valid_df.drop(columns=['interpros', 'esm'])
print(origin_test_df.shape)
print(origin_valid_df.shape)
origin_test_df.head(3)

(3275, 13)
(2870, 13)


index     proteins               accessions     genes  \
58593  430345   RT26_YEAST          P47141; D6VWS0;    853565   
62724  448369  SODF3_ARATH  Q9FMX0; O81240; Q8LCD9;    832395   
62741  448515   SODM_CUPMC  P17550; Q5NUZ9; Q93JN0;  60825782   

                                               sequences  \
58593  MLVFKRGIHVVPKLPNSKALLQNGVPNILSSSGFKTVWFDYQRYLC...   
62724  MSSCVVTTSCFYTISDSSIRLKSPKLLNLSNQQRRRSLRSRGGLKV...   
62741  MLYEMKPLGCEPAKLTGLSEKLIFSHYENNYGGAVKRLNAITATLA...   

                                             annotations          string_ids  \
58593  [GO:0005763|IDA, GO:0005739|HDA, GO:0046872|IE...      [4932.YJR101W]   
62724  [GO:0009507|IDA, GO:0042644|IDA, GO:0009534|IE...  [3702.AT5G23310.1]   
62741   [GO:0046872|IEA, GO:0004784|IDA, GO:0046687|IEA]                  []   

         orgs                                    exp_annotations  \
58593  559292   [GO:0005763, GO:0005739, GO:0003735, GO:0032543]   
62724    3702  [GO:0009507, GO:0042644, GO:0042646, GO:000957...   
62741  266264                                       [GO:0004784]   

                                        prop_annotations  cafa_target  \
58593  [GO:1901566, GO:1901576, GO:0044271, GO:004323...         True   
62724  [GO:0005737, GO:0051716, GO:0043227, GO:000030...         True   
62741  [GO:0051716, GO:0000305, GO:0019430, GO:001672...        False   

                                                    esm2  \
58593  [-0.05179443, -0.0027887435, -0.06578646, -0.0...   
62724  [-0.055271477, -0.022739667, -0.029521158, -0....   
62741  [-0.068125404, -0.08426394, -0.1095703, -0.034...   

                                                mf_preds  
58593  [5.51395669390331e-06, 0.0015262124652508646, ...  
62724  [5.719591513297928e-05, 0.008652074378915131, ...  
62741  [2.7134405627293745e-05, 0.012835425324738026,...

In [6]:
# 将df和origin_df合并，根据proteins列合并
df_test = pd.merge(df_test, origin_test_df, on='proteins')
print(df_test.shape)
df_valid = pd.merge(df_valid, origin_valid_df, on='proteins')
print(df_valid.shape)
df_valid.head(3)

(3275, 15)
(2870, 15)


proteins                                    head_activation  \
0  I17RC_HUMAN  [[1.092963, -0.62294304, -0.027228814, 0.31922...   
1   CGS5_YEAST  [[0.62033427, -0.42075673, -0.02369591, 0.3242...   
2   TCP9_ARATH  [[0.6293054, -0.95022905, -0.025146635, 0.4432...   

                                      mlp_activation   index       accessions  \
0  [[-2.6853547, -2.1375146, -2.2823002, -6.11868...  189970          Q9BR97;   
1  [[-3.4853284, -3.28391, -1.6440333, -5.988611,...   61902  P30283; D6W4B9;   
2  [[-3.0722506, -3.5439043, -1.5122703, -5.96197...  476514          O64647;   

    genes                                          sequences  \
0   84818  MPVPWFLLSLALGRSPVVLSLERLVGPQDATHCSPVSLEPWGDEER...   
1  856237  MGENHDHEQSIKRNSMIYNENERQLCNSNLKILQNKRALSKNDSSS...   
2  819176  MATIQKLEEVAGKDQTLRAVDLTIINGVRNVETSRPFQVNPTVSLE...   

                                         annotations              string_ids  \
0  [GO:0016021|IEA, GO:0005886|TAS, GO:0030368|ID...  [9606.ENSP00000295981]   
1  [GO:0000307|IBA, GO:0005737|IBA, GO:0005634|ID...          [4932.YPR120C]   
2  [GO:0005634|IDA, GO:0003700|ISS, GO:0043565|IB...      [3702.AT2G45680.1]   

     orgs                                    exp_annotations  \
0    9606                           [GO:0005886, GO:0030368]   
1  559292  [GO:0005634, GO:0016538, GO:0000082, GO:000008...   
2    3702  [GO:0005634, GO:0000976, GO:1900056, GO:000836...   

                                    prop_annotations  cafa_target  \
0  [GO:0051716, GO:0030368, GO:0010033, GO:000489...         True   
1  [GO:1901576, GO:0022607, GO:0051128, GO:006023...         True   
2  [GO:1901576, GO:0051252, GO:0044271, GO:007184...         True   

                                                esm2  \
0  [0.025026077, -0.07673664, 0.008636038, -0.008...   
1  [0.026380738, 0.0043458175, 0.036125213, -0.06...   
2  [0.011953792, 0.03907634, 0.02125622, 0.011424...   

                                            mf_preds  
0  [8.268206102002296e-06, 0.01217281143181026, 0...  
1  [4.120965577669722e-07, 0.016200217069126666, ...  
2  [2.4701605951804595e-06, 0.0004813411142094992...

In [7]:
df_valid.to_pickle('../deepgo2/data/bp/valid_esm_data.pkl')
df_test.to_pickle('../deepgo2/data/bp/test_esm_data.pkl')

### 合并保存训练数据激活

In [4]:
dataset_train = Dataset.from_file('dataset/esm2_ctrlprot_dataset/data-00000-of-00089.arrow')
df_train = dataset_train.to_pandas()
# 用for循环读取剩余的35个.arrow文件，并将其转换为Pandas DataFrame，然后追加到df_train
for i in range(1, 89):
    dataset = Dataset.from_file(f'dataset/esm2_ctrlprot_dataset/data-000{i:02}-of-00089.arrow')
    df_train = pd.concat([df_train, dataset.to_pandas()], axis=0)

print(df_train.shape)
df_train.head(3)

(52584, 4)


entry                                           sequence  \
0  SDHF1_YEAST  MPKRLSGLQKEVLHLYRASIRTAHTKPKENQVNFVNYIHEEFGKYR...   
1  SOT18_ARATH  MESETLTAKATITTTTLPSHDETKTESTEFEKNQKRYQDLISTFPH...   
2    MET_HUMAN  MKAPAVLAPGILVLLFTLVQRSNGECKEALAKSEMNVNMKYQLPNF...   

                                     head_activation  \
0  [[0.7016241, -0.9490529, -0.51664203, 0.849823...   
1  [[0.5107845, -0.71882653, 0.38581002, 0.196988...   
2  [[0.8889872, -1.3391258, -0.13748698, 0.425935...   

                                      mlp_activation  
0  [[-4.112434, -3.681763, -0.2170872, -6.5799966...  
1  [[-3.7326634, -3.0547352, -1.9633754, -6.06259...  
2  [[-3.7736533, -3.4933548, -2.3532677, -6.14860...

In [5]:
for i, row in enumerate(df_train.itertuples()):
    print(row.head_activation.shape)
    print(row.head_activation[31])
    if i==3:
        break
for i, row in enumerate(df_train.itertuples()):
    print(row.mlp_activation.shape)
    print(row.mlp_activation[31])
    if i==3:
        break

(33,)
[-0.71588993 -2.0768342   5.04862    ... -2.7151885  -0.78530353
 -3.234813  ]
(33,)
[-1.5260574  -0.19139387  4.4921145  ... -5.255768   -0.08889063
 -5.665192  ]
(33,)
[-0.16226675 -0.5626856  -4.327697   ... -2.3089795  -1.641567
  1.1167527 ]
(33,)
[ 3.2201705  1.4739143 -3.3003402 ... -1.2050488  1.0527704 -1.1452607]
(33,)
[-1.2354145 -2.719276  -2.5441582 ... -1.8417532 -3.4641635 -2.8166165]
(33,)
[-2.3573022 -2.8048196 -3.542714  ... -1.4831424 -3.075628  -2.1320784]
(33,)
[-0.47828695 -1.5647122  -1.0564713  ...  0.7891366  -1.7628084
 -1.4077954 ]
(33,)
[-0.74641734 -1.2265769  -1.4504623  ...  1.0000337  -1.540982
 -0.5161414 ]


In [6]:
df_train = df_train[['entry','sequence', 'head_activation','mlp_activation']]
origin_train_df = pd.read_pickle('../deepgo2/data/bp/train_data.pkl')
origin_train_df = origin_train_df.drop(columns=['interpros', 'esm'])
print(origin_train_df.shape)
# 统计origin_df的proteins列中的字符串是否有重名
print(origin_train_df['proteins'].duplicated().sum())
origin_train_df.head(3)

(52584, 13)
0


index     proteins                       accessions   genes  \
12260   67698  CLE18_ARATH                          Q3ECH9;  842929   
261      2157   5FCL_ARATH  Q8L539; F4K2F3; Q84WD9; Q9FYA5;  831144   
23516  141970   FTHC_YEAST                  P40099; D3DM92;  856932   

                                               sequences  \
12260  MHLLKGGVVLIITLILFLITSSIVAIREDPSLIGVDRQIPTGPDPL...   
261    MIGARVFCITTTALRRSPIFFFPKIPTRPVFRLSPATRPIVAMSTT...   
23516  MATKQLLRRQIKRVINALDYDIIAAESHTISQAVRSLIASANSRRV...   

                                             annotations          string_ids  \
12260  [GO:0048046|ISS, GO:0005615|IEA, GO:0033612|IP...  [3702.AT1G66145.1]   
261    [GO:0005739|IBA, GO:0030272|IDA, GO:0005524|IE...  [3702.AT5G13050.1]   
23516  [GO:0005739|HDA, GO:0030272|IDA, GO:0005524|IE...      [4932.YER183C]   

         orgs                                    exp_annotations  \
12260    3702  [GO:0033612, GO:0010078, GO:0010088, GO:004559...   
261      3702               [GO:0030272, GO:0006952, GO:0046653]   
23516  559292               [GO:0005739, GO:0030272, GO:0009396]   

                                        prop_annotations  cafa_target  \
12260  [GO:0010088, GO:0098727, GO:0019827, GO:001008...         True   
261    [GO:0008152, GO:0071704, GO:0050896, GO:003027...         True   
23516  [GO:0005737, GO:0043227, GO:1901566, GO:190157...         True   

                                                    esm2  \
12260  [-0.0033292728, -0.06586505, 0.1539689, -0.095...   
261    [0.0008405348, -0.053910736, 0.011982507, -0.0...   
23516  [-0.024007985, -0.018454203, 0.030800968, -0.0...   

                                                mf_preds  
12260  [0.0004961845988873392, 0.012308742618188262, ...  
261    [6.477361846890517e-08, 0.08393034338951111, 0...  
23516  [1.877872222166843e-07, 0.05422082915902138, 0...

In [7]:
df_train = df_train[['entry', 'head_activation','mlp_activation']]
df_train = df_train.rename(columns={'entry': 'proteins'})
df_train = pd.merge(df_train, origin_train_df, on='proteins')
print(df_train.shape)
df_train.head(3)

(52584, 15)


proteins                                    head_activation  \
0  SDHF1_YEAST  [[0.7016241, -0.9490529, -0.51664203, 0.849823...   
1  SOT18_ARATH  [[0.5107845, -0.71882653, 0.38581002, 0.196988...   
2    MET_HUMAN  [[0.8889872, -1.3391258, -0.13748698, 0.425935...   

                                      mlp_activation   index  \
0  [[-4.112434, -3.681763, -0.2170872, -6.5799966...  438508   
1  [[-3.7326634, -3.0547352, -1.9633754, -6.06259...  448990   
2  [[-3.7736533, -3.4933548, -2.3532677, -6.14860...  241735   

                                          accessions   genes  \
0                                    Q3E785; D6VT12;  851986   
1                                    Q9C9C9; Q8LA18;  843749   
2  P08581; A1L467; B5A932; E7EQ94; O60366; Q12875...    4233   

                                           sequences  \
0  MPKRLSGLQKEVLHLYRASIRTAHTKPKENQVNFVNYIHEEFGKYR...   
1  MESETLTAKATITTTTLPSHDETKTESTEFEKNQKRYQDLISTFPH...   
2  MKAPAVLAPGILVLLFTLVQRSNGECKEALAKSEMNVNMKYQLPNF...   

                                         annotations              string_ids  \
0  [GO:0005759|IEA, GO:0005739|HDA, GO:0016226|NA...        [4932.YDR379C-A]   
1  [GO:0005737|IBA, GO:0080066|IDA, GO:0080067|ID...      [3702.AT1G74090.1]   
2  [GO:0009925|IDA, GO:0009986|HDA, GO:0005576|IE...  [9606.ENSP00000317272]   

     orgs                                    exp_annotations  \
0  559292                           [GO:0005739, GO:0034553]   
1    3702  [GO:0080066, GO:0080067, GO:0080068, GO:008006...   
2    9606  [GO:0009925, GO:0009986, GO:0005886, GO:004280...   

                                    prop_annotations  cafa_target  \
0  [GO:0005737, GO:0043227, GO:0022607, GO:007184...         True   
1  [GO:0019748, GO:0080071, GO:1901566, GO:190157...         True   
2  [GO:0010638, GO:1901576, GO:0022607, GO:005125...         True   

                                                esm2  \
0  [-0.005900223, -0.06972792, -0.019113254, 0.08...   
1  [0.0012655995, 0.012818696, 0.094285846, -0.05...   
2  [-0.009522585, 0.052666374, 0.009188762, -0.07...   

                                            mf_preds  
0  [4.290521701477701e-05, 0.0017442758253309876,...  
1  [2.9289943483945535e-06, 0.0014401841472135857...  
2  [1.9902781218661403e-06, 0.5326064378023148, 0...

In [8]:
df_train.to_pickle('../deepgo2/data/bp/train_esm_data.pkl')

In [ ]:
th.set_printoptions(edgeitems=5)
data = th.zeros((len(df), 5120), dtype=th.float32)
for i, row in enumerate(df.itertuples()):
        # Data vector
        data[i, :] = th.FloatTensor(row.mlp_activation[0])
        print(data)